### ISSUE TITLE
Setup DCE sandbox on AWS

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#1]
- [x] OS and version Red Hat (CentOS) 7.0
- [ ] Ruby version  ruby 2.1.5 
- [x] Fedora version    Fedora 4.3.0
- [x] Java version  Sun Java JDK 1.8
- [x] Java server   Tomcat 7.0.59
- [x] Solr version  Solr 4.10.3
- [ ] Database      MySQL 5.6.23
- [x] Web server    Apache  2.2.15-39 
- [x] App Server    Passenger 4.0.59

**Comment by acozine** [comment]
For the first demo, I set up wustl.curationexperts.com. It has ruby 2.2.2 and postgresql for a database instead of mysql. Otherwise it matches this list. DCE users, keys, and privileges are active and the machine is currently running the vanilla sufia code from https://github.com/curationexperts/sufia-demo.

**Comment by acozine** [comment]
Confirmed ruby 2.2 and Postgresql are okay.
