### ISSUE TITLE
G-1	Bulk ingest support - TEI metadata

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#130]
> ~~Provide command line import for single file and directory-level ingest of TEI content. (story #37)~~ **Configure appropriate metadata and full-text indexing.**

**Comment by jcoyne** [comment]
Need some acceptance criteria.

**Comment by mark-dce** [comment]
Use the mappings in the Metadata Model spreadsheet:
https://docs.google.com/spreadsheets/d/1UKfW8mOB5M7rtBp09fFT_FztwGppaPer7CLHq9FbbLk/edit#gid=0

See column K for paths within the TEI for
- [x] title
- [x] creator
- [x] identifier
- [x] content license
- [x] publisher
- [ ] subject
- [x] language
- [x] extent
- [x] issue date
- [x] editor

**Comment by val99erie** [comment]
Requirements for identifier, from the spreadsheet:
if no @type exists or @type="dls", then just import value; otherwise, import in the form "#{@type}: #{value}" - e.g. <    idno type="vol">01</idno> becomes 'vol: 01'

**Comment by val99erie** [comment]
@mark-dce  I'm not importing dc:subject as part of this story because the Fanny Lewald sample file doesn't have that field (and I think the SOW only includes importing fields from the Fanny Lewald file).

If we do need to import "subject" fields, could you get a sample file from WUSTL that has those fields and write a new story with the requirements?

For reference, the requirements listed in the spreadsheet were:
- [ ] Read subject from this path:  `<teiHeader><profileDesc><textClass><keywords><term>`
- [ ] May be multiple `<term>` occurrences within `<keywords>`. May be multiple`<keywords>` nodes for different schemas. Import all `<term>` values.
