### ISSUE TITLE
Add collection links

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/goldenseal#185]
- [ ] Add a link to the item's administrative collection on the work's show view
- [ ] Add a link to search for the collection members from the administrative collection show view
## Work Show

Add link to the administrative collection
<img width="817" alt="wustl 185 - collection member link on items" src="https://cloud.githubusercontent.com/assets/3064318/10463668/80336092-71ab-11e5-9ad3-f187f783b071.png">
## Collection Show

Add link to search for members
<img width="829" alt="wustl 185 - collection member link on show page" src="https://cloud.githubusercontent.com/assets/3064318/10463690/9307b33a-71ab-11e5-8d8a-4d2ce22b167d.png">
## Collection member search example

The button on the collection show page should give results something like this
<img width="814" alt="wustl 185 - collection member search results" src="https://cloud.githubusercontent.com/assets/3064318/10463705/a7ae73fa-71ab-11e5-90e1-930d828f4fb3.png">

**Comment by mark-dce** [comment]
When I use the face link to view the collection members, I get this:
http://wustl.curationexperts.com/catalog?f%5Badmin_set_ssi%5D%5B%5D=America%27s+War+On+Poverty&q=&search_field=all_fields

## BUG # 1

When I click the "View Members" from the [Collection Show Page](http://wustl.curationexperts.com/admin_sets/awp), I get this:
http://wustl.curationexperts.com/catalog?q=America%27s+War+On+Poverty&search_field=admin_set

It looks like the encoding isn't correct on the latter if you look at the text in the search box - and it gives you the search results for the collection, not it's members.

## BUG # 2

When I click on the Administrative Collection link on an individual work in the collection, I get this: 
http://wustl.curationexperts.com/catalog?q=America%26%2339%3Bs+War+On+Poverty&search_field=admin_set
I should just get a link to http://wustl.curationexperts.com/admin_sets/awp

**Comment by jcoyne** [comment]
Sufia does link_to_facet:
https://github.com/projecthydra/sufia/blob/master/app/views/records/show_fields/_creator.html.erb#L3
or link_to_field
https://github.com/projecthydra/sufia/blob/master/app/views/records/show_fields/_rights.html.erb

Whereas curation_concerns only has  search_path: https://github.com/projecthydra-labs/curation_concerns/blob/master/app/renderers/attribute_renderer.rb#L53-L56

We should allow curation_concerns to have a link_to_face and fix the search path so that it works like link_to_field does in Sufia.
