### ISSUE TITLE
 Receive a page doesn't exist message after video ingest

### ISSUE THREAD

**Issue by msellan** [curationexperts/goldenseal#235]
I ingest a video and received the page showing the generic thumbnail.  If I click that thumbnail I get an error screen saying "The page you were looking for doesn't exist" the production.log logs a 404 error rather than either the video or a screen that says the video is processing or something like that.

**Comment by mark-dce** [comment]
@msellan 

We've been able to reproduce this issue under two  circumstances, 
(1) When uploading videos (or potentially very long audio), the derivative processing is handled in the background.  Depending on the length/size of the media, other load on the server, and other ingest jobs being run, there will be a delay between the time a file attachment container is created for the derivative media and the time the completely transcoded derivative is written to the object.  In this case, the issue will resolve itself within a few seconds to a number of minutes (depending on the length of the media clip and other system load)
(2) A similar situation can occur in conjunction with resque workers crashing due to lack of system resources.   In this state, the thumbnail will continue to give a 404 error until the workers are restarted and the derivatives jobs complete.  Unfortunately, resque worker crashes cannot be detected easily at the rails level and processed outside the rails environment are better suited to monitoring and restarting the workers processes.  You can detect this situation by logging into the application as an administrator and viewing the Resque overview by clicking on the jobs link in the user menu (under your login name in the header bar) - if the summary page says "0 of 0 Workers Working", that indicates no workers are running and the resque worker processes need to be restarted.  We would recommend setting up nagios or a similar system monitoring tool to monitor resque processes (processes with 'resque' in the name) and triggering alerts if the actual number of process falls below the expected number.
