### ISSUE TITLE
Import the DC metadata

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#36]
In `/opt/sample-data/DCE_WU_content_model/DC-fromDLXScolls/*.xml`

**Comment by val99erie** [comment]
Question:  How will we know what type of work to create? (e.g. Audio, Video, Image, or Document).  The XML file with the DC metadata doesn't have any fields that will tell us what type of record it is.

**Comment by val99erie** [comment]
We need to confirm this with the wustl team:
- [ ] For each collection in DLXS, are all the records within the collection the same type of work?  (e.g.  If it's a video collection, are all the members of the collection videos, or are there sometimes audio and image works in the collection too?)

If the members of a collection are always only one type of work, then we could have the user pass the work type on the command line, instead of having the DC importer try to figure out what type of work to create.

**Comment by acozine** [comment]
Since all the sample collections WUSTL has provided contain files that are all of the same type (text only, image and text, video, etc.), we will create an importer that specifies a file for the DC collection metadata, a work type for the objects in the collection, and a directory for the files and metadata for the objects (or a requirement that the files and the DC metadata file reside in the same directory).
