### ISSUE TITLE
G-1: Import TEI metadata and videos

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#39]
in `/opt/sample-data/DCE_WU_content_model/great-depression-TEI-textvideo`

**Comment by val99erie** [comment]
The WUSTL team have identified the collection "America's War on Poverty" as the primary sample data that we should test the importer against.  As of today, we don't have sample data for that collection, but we have sample data for another collection, "The Great Depression".

**Comment by acozine** [comment]
Sample data for America's War on Poverty is on the server now - see #48 for details.

**Comment by mark-dce** [comment]
The behavior of the importer should be similar to the TEI Text importer.
- [x] The importer should take the path to a directory containing one or more TEI transcripts,  and an optional parameter to set the access level [open, institution, private]
- [x] The importer should search for associated video/audio files in the directory where the transcript is and it's children

Import the following fields
- [x] **title** /TEI/teiHeader/fileDesc/titleStmt/title
  Make sure to add space if there are internal nodes
- [x] **creator** /TEI/teiHeader/fileDesc/sourceDesc/recordingStmt/recording/respStmt/name  
- [x] **contributor** /TEI/teiHeader/fileDesc/sourceDesc/recordingStmt/recording/respStmt/name  
- [x] **description** /TEI/text/front/titlePage/imprimatur  
- [x] **Identifier** /TEI/teiHeader/fileDesc/sourceDesc/recordingStmt/recording/date  
  if no @type exists or @type="dls", then just import value; otherwise, import in the form "#{@type}: #{value}" - e.g. <idno type="vol">01</idno> becomes 'vol: 01'
- [x] **content license** /TEI/teiHeader/fileDesc/publicationStmt/availability  
  "work is in the public domain" maps to "Public Domain Mark 1.0", all others map to "All Rights Reserved"
- [x] **publisher** /TEI/teiHeader/fileDesc/publicationStmt/publisher  
- [x] **subject** /TEI/teiHeader/profileDesc/textClass/keywords  
  There may be multiple keyword nodes representing multiple authorited, import all keywords from all nodes
- [x] **language** /TEI/teiHeader/profileDesc/langUsage/language  
- [x] **date_created** /TEI/teiHeader/fileDesc/sourceDesc/recordingStmt/recording/date  
- [x] **issued**/TEI/teiHeader/fileDesc/publicationStmt/date  
- [x] **publication_place** /TEI/teiHeader/fileDesc/publicationStmt/pubPlace

Sample data is located in /opt/sample-data/Americas_War_on_Poverty

**Comment by val99erie** [comment]
Question:  How do I figure out which files should be attached to the work?  For example, in the sample-data directory, I see a file called fma-2-78436-acc-20140424.mov, but I don't see it anywhere in any of the TEI files.

**Comment by val99erie** [comment]
Question:  Does this story only cover creation of Video objects?  Are Audio objects handled in a different story?

Answer: Per Mark, the importer should handle both Video and Audio imports.

**Comment by mark-dce** [comment]
Look for the filename of the associated video or audio file in /TEI/teiHeader/fileDesc/sourceDesc/recordingStmt/recording/media/@url

These sample transcripts have the correct file names included at this node:
- add14885.01250.032-cleaned.xml
- ~~avi14885.00654.023-cleaned.xml~~ [not tested yet]

The file importer should look for any file with a matching name in the same directory or sub-directory (like the TEI Text importer searches for page images)

**Comment by val99erie** [comment]
@mark-dce I assume that you mean `teiHeader/fileDesc/publicationStmt/idno` for identifier.  Let me know if that's not correct.

**Comment by mark-dce** [comment]
@val99erie Yes, you're right - that was a serious cut and paste error on my part.

**Comment by mark-dce** [comment]
After our disk cleanup, the sample data is now at `/data/americas_war_on_poverty/`

**Comment by val99erie** [comment]
@mark-dce  Do we have any sample data for Audio works?

**Comment by mark-dce** [comment]
Val - no they don't have any audio specific content.  I added audio only versions of the America's War on Poverty interviews - the transcripts should be identical, so you should get the behavior of the player playing the audio track with transcript sync.

**SAMPLES**
/data/audio_only_war_on_poverty

There are both .wav and .mp3 versions of the audio in that directory.  The TEI files point at the WAV versions.  There's alot of blank audio at the beginning of the clip where the title screen etc. were.
